"""
Standard list of 63 Provinces and Cities of Vietnam.
Used to enhance Location-based Trend Detection and Alias Normalization.
"""

VIETNAM_PROVINCES = [
    "An Giang", "Bà Rịa – Vũng Tàu", "Bạc Liêu", "Bắc Giang", "Bắc Kạn", "Bắc Ninh", 
    "Bến Tre", "Bình Dương", "Bình Định", "Bình Phước", "Bình Thuận", "Cà Mau", 
    "Cao Bằng", "Cần Thơ", "Đà Nẵng", "Đắk Lắk", "Đắk Nông", "Điện Biên", "Đồng Nai", 
    "Đồng Tháp", "Gia Lai", "Hà Giang", "Hà Nam", "Hà Nội", "Hà Tĩnh", "Hải Dương", 
    "Hải Phòng", "Hậu Giang", "Hòa Bình", "Hưng Yên", "Khánh Hòa", "Kiên Giang", 
    "Kon Tum", "Lai Châu", "Lạng Sơn", "Lào Cai", "Lâm Đồng", "Long An", "Nam Định", 
    "Nghệ An", "Ninh Bình", "Ninh Thuận", "Phú Thọ", "Phú Yên", "Quảng Bình", 
    "Quảng Nam", "Quảng Ngãi", "Quảng Ninh", "Quảng Trị", "Sóc Trăng", "Sơn La", 
    "Tây Ninh", "Thái Bình", "Thái Nguyên", "Thanh Hóa", "Thừa Thiên Huế", "Tiền Giang", 
    "TP. Hồ Chí Minh", "Trà Vinh", "Tuyên Quang", "Vĩnh Long", "Vĩnh Phúc", "Yên Bái"
]

# Common aliases for major cities
LOCATION_ALIASES = {
    "TP. Hồ Chí Minh": ["Sài Gòn", "HCM", "TPHCM", "Thành phố Hồ Chí Minh"],
    "Hà Nội": ["Thủ đô", "Hanoi"],
    "Đà Nẵng": ["Da Nang"],
    "Thừa Thiên Huế": ["Huế"],
    "Hải Phòng": ["Thành phố Cảng"],
    "Bà Rịa – Vũng Tàu": ["Vũng Tàu", "BRVT"]
}

# Popular International Countries (Vietnamese names and English aliases)
POPULAR_COUNTRIES = {
    # ===== Châu Phi (54) =====
    "Afghanistan": ["Afghanistan"],
    "Albania": ["Albania"],
    "Algeria": ["Algeria"],
    "Angola": ["Angola"],
    "Benin": ["Benin"],
    "Botswana": ["Botswana"],
    "Burkina Faso": ["Burkina Faso"],
    "Burundi": ["Burundi"],
    "Cabo Verde": ["Cape Verde"],
    "Cameroon": ["Cameroon"],
    "Central African Republic": ["Central African Republic"],
    "Chad": ["Chad"],
    "Comoros": ["Comoros"],
    "Republic of the Congo": ["Republic of the Congo", "Congo"],
    "Democratic Republic of the Congo": ["Democratic Republic of the Congo", "DRC"],
    "Djibouti": ["Djibouti"],
    "Egypt": ["Egypt"],
    "Equatorial Guinea": ["Equatorial Guinea"],
    "Eritrea": ["Eritrea"],
    "Eswatini": ["Eswatini", "Swaziland"],
    "Ethiopia": ["Ethiopia"],
    "Gabon": ["Gabon"],
    "Gambia": ["Gambia"],
    "Ghana": ["Ghana"],
    "Guinea": ["Guinea"],
    "Guinea-Bissau": ["Guinea-Bissau"],
    "Ivory Coast": ["Côte d’Ivoire", "Ivory Coast"],
    "Kenya": ["Kenya"],
    "Lesotho": ["Lesotho"],
    "Liberia": ["Liberia"],
    "Libya": ["Libya"],
    "Madagascar": ["Madagascar"],
    "Malawi": ["Malawi"],
    "Mali": ["Mali"],
    "Mauritania": ["Mauritania"],
    "Mauritius": ["Mauritius"],
    "Morocco": ["Morocco"],
    "Mozambique": ["Mozambique"],
    "Namibia": ["Namibia"],
    "Niger": ["Niger"],
    "Nigeria": ["Nigeria"],
    "Rwanda": ["Rwanda"],
    "Sao Tome and Principe": ["Sao Tome and Principe"],
    "Senegal": ["Senegal"],
    "Seychelles": ["Seychelles"],
    "Sierra Leone": ["Sierra Leone"],
    "Somalia": ["Somalia"],
    "South Africa": ["South Africa"],
    "South Sudan": ["South Sudan"],
    "Sudan": ["Sudan"],
    "Tanzania": ["Tanzania"],
    "Togo": ["Togo"],
    "Tunisia": ["Tunisia"],
    "Uganda": ["Uganda"],
    "Zambia": ["Zambia"],
    "Zimbabwe": ["Zimbabwe"],

    # ===== Châu Á (49) =====
    "Armenia": ["Armenia"],
    "Azerbaijan": ["Azerbaijan"],
    "Bahrain": ["Bahrain"],
    "Bangladesh": ["Bangladesh"],
    "Bhutan": ["Bhutan"],
    "Brunei": ["Brunei"],
    "Cambodia": ["Cambodia"],
    "China": ["China", "PRC"],
    "Cyprus": ["Cyprus"],
    "Georgia": ["Georgia"],
    "India": ["India"],
    "Indonesia": ["Indonesia"],
    "Iran": ["Iran"],
    "Iraq": ["Iraq"],
    "Israel": ["Israel"],
    "Japan": ["Japan"],
    "Jordan": ["Jordan"],
    "Kazakhstan": ["Kazakhstan"],
    "Kuwait": ["Kuwait"],
    "Kyrgyzstan": ["Kyrgyzstan"],
    "Laos": ["Laos"],
    "Lebanon": ["Lebanon"],
    "Malaysia": ["Malaysia"],
    "Maldives": ["Maldives"],
    "Mongolia": ["Mongolia"],
    "Myanmar": ["Myanmar", "Burma"],
    "Nepal": ["Nepal"],
    "North Korea": ["North Korea", "DPRK"],
    "Oman": ["Oman"],
    "Pakistan": ["Pakistan"],
    "Philippines": ["Philippines"],
    "Qatar": ["Qatar"],
    "Saudi Arabia": ["Saudi Arabia"],
    "Singapore": ["Singapore"],
    "South Korea": ["South Korea", "Republic of Korea"],
    "Sri Lanka": ["Sri Lanka"],
    "Syria": ["Syria"],
    "Tajikistan": ["Tajikistan"],
    "Thailand": ["Thailand"],
    "Timor-Leste": ["Timor-Leste", "East Timor"],
    "Turkey": ["Turkey", "Türkiye"],
    "Turkmenistan": ["Turkmenistan"],
    "United Arab Emirates": ["United Arab Emirates", "UAE"],
    "Uzbekistan": ["Uzbekistan"],
    "Vietnam": ["Vietnam", "Viet Nam"],
    "Yemen": ["Yemen"],

    # ===== Châu Âu (44) =====
    "Austria": ["Austria"],
    "Belarus": ["Belarus"],
    "Belgium": ["Belgium"],
    "Bosnia and Herzegovina": ["Bosnia and Herzegovina"],
    "Bulgaria": ["Bulgaria"],
    "Croatia": ["Croatia"],
    "Czech Republic": ["Czech Republic", "Czechia"],
    "Denmark": ["Denmark"],
    "Estonia": ["Estonia"],
    "Finland": ["Finland"],
    "France": ["France"],
    "Germany": ["Germany"],
    "Greece": ["Greece"],
    "Hungary": ["Hungary"],
    "Iceland": ["Iceland"],
    "Ireland": ["Ireland"],
    "Italy": ["Italy"],
    "Latvia": ["Latvia"],
    "Liechtenstein": ["Liechtenstein"],
    "Lithuania": ["Lithuania"],
    "Luxembourg": ["Luxembourg"],
    "Malta": ["Malta"],
    "Moldova": ["Moldova"],
    "Monaco": ["Monaco"],
    "Montenegro": ["Montenegro"],
    "Netherlands": ["Netherlands", "Holland"],
    "North Macedonia": ["North Macedonia"],
    "Norway": ["Norway"],
    "Poland": ["Poland"],
    "Portugal": ["Portugal"],
    "Romania": ["Romania"],
    "Russia": ["Russia", "Russian Federation"],
    "San Marino": ["San Marino"],
    "Serbia": ["Serbia"],
    "Slovakia": ["Slovakia"],
    "Slovenia": ["Slovenia"],
    "Spain": ["Spain"],
    "Sweden": ["Sweden"],
    "Switzerland": ["Switzerland"],
    "Ukraine": ["Ukraine"],
    "United Kingdom": ["United Kingdom", "UK", "Britain"],
    "Vatican City": [],  # ❌ không phải UN member
    "Kosovo": [],        # ❌ không phải UN member

    # ===== Châu Mỹ (35) =====
    "Antigua and Barbuda": ["Antigua and Barbuda"],
    "Argentina": ["Argentina"],
    "Bahamas": ["Bahamas"],
    "Barbados": ["Barbados"],
    "Belize": ["Belize"],
    "Bolivia": ["Bolivia"],
    "Brazil": ["Brazil"],
    "Canada": ["Canada"],
    "Chile": ["Chile"],
    "Colombia": ["Colombia"],
    "Costa Rica": ["Costa Rica"],
    "Cuba": ["Cuba"],
    "Dominica": ["Dominica"],
    "Dominican Republic": ["Dominican Republic"],
    "Ecuador": ["Ecuador"],
    "El Salvador": ["El Salvador"],
    "Grenada": ["Grenada"],
    "Guatemala": ["Guatemala"],
    "Guyana": ["Guyana"],
    "Haiti": ["Haiti"],
    "Honduras": ["Honduras"],
    "Jamaica": ["Jamaica"],
    "Mexico": ["Mexico"],
    "Nicaragua": ["Nicaragua"],
    "Panama": ["Panama"],
    "Paraguay": ["Paraguay"],
    "Peru": ["Peru"],
    "Saint Kitts and Nevis": ["Saint Kitts and Nevis"],
    "Saint Lucia": ["Saint Lucia"],
    "Saint Vincent and the Grenadines": ["Saint Vincent and the Grenadines"],
    "Suriname": ["Suriname"],
    "Trinidad and Tobago": ["Trinidad and Tobago"],
    "United States": ["United States", "USA", "US"],
    "Uruguay": ["Uruguay"],
    "Venezuela": ["Venezuela"],

    # ===== Châu Đại Dương (11) =====
    "Australia": ["Australia"],
    "Fiji": ["Fiji"],
    "Kiribati": ["Kiribati"],
    "Marshall Islands": ["Marshall Islands"],
    "Micronesia": ["Micronesia"],
    "Nauru": ["Nauru"],
    "New Zealand": ["New Zealand"],
    "Palau": ["Palau"],
    "Papua New Guinea": ["Papua New Guinea"],
    "Samoa": ["Samoa"],
    "Solomon Islands": ["Solomon Islands"],
    "Tonga": ["Tonga"],
    "Tuvalu": ["Tuvalu"],
    "Vanuatu": ["Vanuatu"]
}

POPULAR_CITIES = {
    # ===== Special Administrative Regions / Special Cities =====
    "Hong Kong": ["Hong Kong", "HK", "HKSAR"],
    "Macau": ["Macau", "Macao"],
    "Taipei": ["Taipei"],

    # ===== Americas =====
    "Washington, D.C.": ["Washington", "Washington DC", "D.C."],
    "New York": ["New York", "NYC", "New York City"],
    "Los Angeles": ["Los Angeles", "LA"],
    "San Francisco": ["San Francisco", "SF"],
    "Chicago": ["Chicago"],
    "Toronto": ["Toronto"],
    "Vancouver": ["Vancouver"],
    "Mexico City": ["Mexico City"],
    "São Paulo": ["Sao Paulo", "São Paulo"],
    "Rio de Janeiro": ["Rio de Janeiro", "Rio"],
    "Buenos Aires": ["Buenos Aires"],

    # ===== Europe =====
    "London": ["London"],
    "Paris": ["Paris"],
    "Berlin": ["Berlin"],
    "Rome": ["Rome"],
    "Madrid": ["Madrid"],
    "Barcelona": ["Barcelona"],
    "Amsterdam": ["Amsterdam"],
    "Brussels": ["Brussels"],
    "Vienna": ["Vienna"],
    "Prague": ["Prague"],
    "Warsaw": ["Warsaw"],
    "Budapest": ["Budapest"],
    "Athens": ["Athens"],
    "Stockholm": ["Stockholm"],
    "Oslo": ["Oslo"],
    "Copenhagen": ["Copenhagen"],
    "Helsinki": ["Helsinki"],
    "Zurich": ["Zurich"],
    "Geneva": ["Geneva"],
    "Moscow": ["Moscow"],
    "Saint Petersburg": ["Saint Petersburg", "St. Petersburg"],
    "Kyiv": ["Kyiv", "Kiev"],

    # ===== East Asia =====
    "Beijing": ["Beijing", "Peking"],
    "Shanghai": ["Shanghai"],
    "Shenzhen": ["Shenzhen"],
    "Guangzhou": ["Guangzhou", "Canton"],
    "Tokyo": ["Tokyo"],
    "Osaka": ["Osaka"],
    "Kyoto": ["Kyoto"],
    "Seoul": ["Seoul"],
    "Busan": ["Busan"],
    "Pyongyang": ["Pyongyang"],

    # ===== Southeast Asia =====
    "Hanoi": ["Hanoi", "Ha Noi"],
    "Ho Chi Minh City": ["Ho Chi Minh City", "HCMC", "Saigon"],
    "Bangkok": ["Bangkok"],
    "Singapore": ["Singapore"],
    "Kuala Lumpur": ["Kuala Lumpur", "KL"],
    "Jakarta": ["Jakarta"],
    "Manila": ["Manila"],
    "Phnom Penh": ["Phnom Penh"],
    "Vientiane": ["Vientiane"],
    "Yangon": ["Yangon", "Rangoon"],

    # ===== South Asia =====
    "New Delhi": ["New Delhi", "Delhi"],
    "Mumbai": ["Mumbai", "Bombay"],
    "Bangalore": ["Bangalore", "Bengaluru"],
    "Dhaka": ["Dhaka"],
    "Karachi": ["Karachi"],
    "Colombo": ["Colombo"],
    "Kathmandu": ["Kathmandu"],

    # ===== Middle East =====
    "Jerusalem": ["Jerusalem"],
    "Tel Aviv": ["Tel Aviv"],
    "Riyadh": ["Riyadh"],
    "Dubai": ["Dubai"],
    "Abu Dhabi": ["Abu Dhabi"],
    "Doha": ["Doha"],
    "Tehran": ["Tehran"],
    "Baghdad": ["Baghdad"],
    "Istanbul": ["Istanbul"],
    "Ankara": ["Ankara"],

    # ===== Africa =====
    "Cairo": ["Cairo"],
    "Alexandria": ["Alexandria"],
    "Johannesburg": ["Johannesburg"],
    "Pretoria": ["Pretoria"],
    "Cape Town": ["Cape Town"],
    "Nairobi": ["Nairobi"],
    "Lagos": ["Lagos"],
    "Accra": ["Accra"],
    "Addis Ababa": ["Addis Ababa"],
    "Casablanca": ["Casablanca"],
    "Tunis": ["Tunis"],
    "Algiers": ["Algiers"],

    # ===== Oceania =====
    "Canberra": ["Canberra"],
    "Sydney": ["Sydney"],
    "Melbourne": ["Melbourne"],
    "Auckland": ["Auckland"],
    "Wellington": ["Wellington"]
}


def get_known_locations():
    """Returns a flat list of all province names, countries, and their major aliases."""
    all_locs = set(VIETNAM_PROVINCES)
    for aliases in LOCATION_ALIASES.values():
        all_locs.update(aliases)
    
    for country, aliases in POPULAR_COUNTRIES.items():
        all_locs.add(country)
        all_locs.update(aliases)
    
    for city, aliases in POPULAR_CITIES.items():
        all_locs.add(city)
        all_locs.update(aliases)
        
    return sorted(list(all_locs))
