import numpy as np
import pandas as pd
from sentence_transformers import SentenceTransformer
from sklearn.metrics.pairwise import cosine_similarity
import os

# CONFIG
DATA_DIR = '../demo/demo_data'  # Target directory
MODEL_NAME = 'dangvantuan/vietnamese-document-embedding'

def verify():
    print(f"🧐 Verifying data in: {DATA_DIR}")
    
    # 1. Load Data
    try:
        embeddings = np.load(os.path.join(DATA_DIR, 'post_embeddings.npy'))
        df = pd.read_parquet(os.path.join(DATA_DIR, 'results.parquet'))
        print(f"   ✅ Loaded {len(df)} posts and embeddings shape {embeddings.shape}")
    except Exception as e:
        print(f"   ❌ Failed to load data: {e}")
        return

    # 2. Load Model
    print(f"   📥 Loading model: {MODEL_NAME}...")
    model = SentenceTransformer(MODEL_NAME, trust_remote_code=True)

    # 3. Test a random sample
    sample_idx = 0
    sample_text = df.iloc[sample_idx]['content']
    stored_emb = embeddings[sample_idx].reshape(1, -1)

    print(f"   🧪 Testing post: '{sample_text[:50]}...'")
    
    # Compute fresh embedding
    fresh_emb = model.encode([sample_text])
    
    # Compare
    sim = cosine_similarity(stored_emb, fresh_emb)[0][0]
    print(f"   📊 Cosine Similarity (Stored vs Fresh): {sim:.4f}")

    if sim > 0.99:
        print("   ✅ MATCH CONFIRMED! This data works with your model.")
    else:
        print("   ❌ MISMATCH! These embeddings were generated by a different model.")

if __name__ == "__main__":
    verify()
